name = "onedrive"
type = "webpack"
workers_dev = true
account_id = "b1a1490a068338927f9a2fd23af1f0ce"
zone_id = "6ee29dc1e4329e370f50a5a167420330"
kv_namespaces = [
    { binding = "BUCKET", preview_id = "cf8da32bee0d436384d70b9a3f2250eb", id = "cf8da32bee0d436384d70b9a3f2250eb" }
]

[env.staging]
name = "drive-staging"
